Complain if output dir, cache dir or runtime dir does not exist

diff --git a/linux/build b/linux/build
--- a/linux/build
+++ b/linux/build
@@ -108,8 +108,16 @@ function parse_options()
 			echo "ERROR: please specify a cache directory with -c."
 			exit 1
 		fi
+		if [[ ! -e "$CACHE_DIR" ]]; then
+			echo "ERROR: $CACHE_DIR does not exist."
+			exit 1
+		fi
 		if [[ "$OUTPUT_DIR" = "" ]]; then
 			echo "ERROR: please specify an output directory with -o."
+			exit 1
+		fi
+		if [[ ! -e "$OUTPUT_DIR" ]]; then
+			echo "ERROR: $OUTPUT_DIR does not exist."
 			exit 1
 		fi
 		if [[ "$ARCHITECTURE" = "" ]]; then
@@ -162,9 +170,6 @@ else
 			EXTRA_DOCKER_ARGS+=(-e "NGINX_VERSION=$NGINX_VERSION")
 		fi
 	fi
-
-	run mkdir -p "$CACHE_DIR"
-	run mkdir -p "$OUTPUT_DIR"
 
 	echo "-------- Entering Docker container --------"
 	exec docker run -t -i --rm \
diff --git a/macos/build b/macos/build
--- a/macos/build
+++ b/macos/build
@@ -115,8 +115,16 @@ function parse_options()
 			echo "ERROR: please specify a cache directory with -c."
 			exit 1
 		fi
+		if [[ ! -e "$CACHE_DIR" ]]; then
+			echo "ERROR: $CACHE_DIR does not exist."
+			exit 1
+		fi
 		if [[ "$OUTPUT_DIR" = "" ]]; then
 			echo "ERROR: please specify an output directory with -o."
+			exit 1
+		fi
+		if [[ ! -e "$OUTPUT_DIR" ]]; then
+			echo "ERROR: $OUTPUT_DIR does not exist."
 			exit 1
 		fi
 		if [[ "$NGINX_DIR" != "" ]]; then
@@ -168,9 +176,6 @@ else
 		export NGINX_VERSION
 	fi
 	export CONCURRENCY
-
-	run mkdir -p "$CACHE_DIR"
-	run mkdir -p "$OUTPUT_DIR"
 
 	exec /usr/local/bin/drake -f "$ROOTDIR/shared/build/Rakefile" "${ARGV[@]}"
 fi
diff --git a/macos/setup-runtime b/macos/setup-runtime
--- a/macos/setup-runtime
+++ b/macos/setup-runtime
@@ -50,8 +50,16 @@ function parse_options()
 		esac
 	done
 
+	if [[ ! -e "$CACHE_DIR" ]]; then
+		echo "ERROR: $CACHE_DIR does not exist."
+		exit 1
+	fi
 	if [[ "$OUTPUT_DIR" = "" ]]; then
 		echo "ERROR: please specify an output directory with -o."
+		exit 1
+	fi
+	if [[ ! -e "$OUTPUT_DIR" ]]; then
+		echo "ERROR: $OUTPUT_DIR does not exist."
 		exit 1
 	fi
 }
@@ -71,7 +79,6 @@ export PATH="$ROOTDIR/macos/support/bin:$RUNTIME_DIR/bin:$PATH"
 if [[ "$CACHE_DIR" != "" ]]; then
 	export CACHE_DIR="`absolute_path \"$CACHE_DIR\"`"
 	export CCACHE_DIR="$CACHE_DIR/ccache-runtime"
-	run mkdir -p "$CCACHE_DIR"
 fi
 
 export WORKDIR=`mktemp -d /tmp/pbba.XXXXXX`
@@ -80,7 +87,6 @@ function cleanup()
 	run rm -rf "$WORKDIR"
 }
 
-run mkdir -p "$OUTPUT_DIR"
 cd "$WORKDIR"
 
 if [[ ! -e "$OUTPUT_DIR/bin/ccache" ]]; then
